services:
  agent:
    ports:
    - 4242:4242
    volumes:
    - .:/dp-agent
  convers-evaluator-annotator:
    ports:
    - 8004:8004
    volumes:
    - ./annotators/ConversationEvaluator:/src
    - ~/.deeppavlov:/root/.deeppavlov
  dff-intent-responder-skill:
    ports:
    - 8012:8012
    volumes:
    - ./skills/dff_intent_responder_skill:/src
    - ./common:/src/common
  dff-weather-skill:
    ports:
    - 8037:8037
    volumes:
    - ./skills/dff_weather_skill:/src
    - ./common:/src/common
  dialogpt:
    ports:
    - 8125:8125
    volumes:
    - ./services/dialogpt:/src
    - ./common:/src/common
  entity-detection:
    ports:
    - 8103:8103
    volumes:
    - ./annotators/entity_detection:/src
    - ~/.deeppavlov:/root/.deeppavlov
  intent-catcher:
    ports:
    - 8014:8014
    volumes:
    - ./annotators/IntentCatcherTransformers:/src
    - ./common:/src/common
    - ~/.deeppavlov:/root/.deeppavlov
  mongo:
    ports:
    - 27017:27017
  ner:
    ports:
    - 8021:8021
    volumes:
    - ./annotators/NER_deeppavlov:/src
    - ~/.deeppavlov:/root/.deeppavlov
  sentseg:
    ports:
    - 8011:8011
    volumes:
    - ./annotators/SentSeg:/src
  spacy-nounphrases:
    ports:
    - 8006:8006
    volumes:
    - ./annotators/spacy_nounphrases:/src
    - ./common:/src/common
  spelling-preprocessing:
    ports:
    - 8074:8074
    volumes:
    - ./annotators/spelling_preprocessing:/src
version: '3.7'
