services:
  agent:
    volumes:
    - .:/dp-agent
    ports:
    - 4242:4242
  convers-evaluator-annotator:
    volumes:
    - ./annotators/ConversationEvaluator:/src
    - ~/.deeppavlov:/root/.deeppavlov
    ports:
    - 8004:8004
  spacy-nounphrases:
    volumes:
    - ./annotators/spacy_nounphrases:/src
    - ./common:/src/common
    ports:
    - 8006:8006
  sentseg:
    volumes:
    - ./annotators/SentSeg:/src
    ports:
    - 8011:8011
  dff-intent-responder-skill:
    volumes:
    - ./skills/dff_intent_responder_skill:/src
    - ./common:/src/common
    ports:
    - 8012:8012
  intent-catcher:
    volumes:
    - ./annotators/IntentCatcherTransformers:/src
    - ./common:/src/common
    - ~/.deeppavlov:/root/.deeppavlov
    - ~/.deeppavlov/cache:/root/.cache
    ports:
    - 8014:8014
  ner:
    volumes:
    - ./annotators/NER_deeppavlov:/src
    - ~/.deeppavlov:/root/.deeppavlov
    ports:
    - 8021:8021
  mongo:
    ports:
    - 27017:27017
  spelling-preprocessing:
    volumes:
    - ./annotators/spelling_preprocessing:/src
    ports:
    - 8074:8074
  entity-detection:
    volumes:
    - ./annotators/entity_detection:/src
    - ~/.deeppavlov:/root/.deeppavlov
    - ~/.deeppavlov/cache:/root/.cache
    ports:
    - 8103:8103
  dff-weather-skill:
    volumes:
    - ./skills/dff_weather_skill:/src
    - ./common:/src/common
    ports:
    - 8037:8037
  dialogpt:
    volumes:
    - ./services/dialogpt:/src
    - ./common:/src/common
    - ~/.deeppavlov/cache:/root/.cache
    ports:
    - 8125:8125
version: '3.7'
