services:
  convers-evaluator-annotator:
    build:
      context: dp/proxy
      dockerfile: Dockerfile
    command:
    - nginx
    - -g
    - daemon off;
    environment:
    - PROXY_PASS=dream.deeppavlov.ai:8004
    - PORT=8004
  sentseg:
    build:
      context: dp/proxy
      dockerfile: Dockerfile
    command:
    - nginx
    - -g
    - daemon off;
    environment:
    - PROXY_PASS=dream.deeppavlov.ai:8011
    - PORT=8011
  dff-intent-responder-skill:
    build:
      context: dp/proxy
      dockerfile: Dockerfile
    command:
    - nginx
    - -g
    - daemon off;
    environment:
    - PROXY_PASS=dream.deeppavlov.ai:8012
    - PORT=8012
  intent-catcher:
    build:
      context: dp/proxy
      dockerfile: Dockerfile
    command:
    - nginx
    - -g
    - daemon off;
    environment:
    - PROXY_PASS=dream.deeppavlov.ai:8014
    - PORT=8014
  ner:
    build:
      context: dp/proxy
      dockerfile: Dockerfile
    command:
    - nginx
    - -g
    - daemon off;
    environment:
    - PROXY_PASS=dream.deeppavlov.ai:8021
    - PORT=8021
  spelling-preprocessing:
    build:
      context: dp/proxy
      dockerfile: Dockerfile
    command:
    - nginx
    - -g
    - daemon off;
    environment:
    - PROXY_PASS=dream.deeppavlov.ai:8074
    - PORT=8074
  entity-detection:
    build:
      context: dp/proxy
      dockerfile: Dockerfile
    command:
    - nginx
    - -g
    - daemon off;
    environment:
    - PROXY_PASS=dream.deeppavlov.ai:8103
    - PORT=8103
  spacy-nounphrases:
    build:
      context: dp/proxy
      dockerfile: Dockerfile
    command:
    - nginx
    - -g
    - daemon off;
    environment:
    - PROXY_PASS=dream.deeppavlov.ai:8006
    - PORT=8006
  dff-weather-skill:
    build:
      context: dp/proxy
      dockerfile: Dockerfile
    command:
    - nginx
    - -g
    - daemon off;
    environment:
    - PROXY_PASS=dream.deeppavlov.ai:8037
    - PORT=8037
  dialogpt:
    build:
      context: dp/proxy
      dockerfile: Dockerfile
    command:
    - nginx
    - -g
    - daemon off;
    environment:
    - PROXY_PASS=dream.deeppavlov.ai:8125
    - PORT=8125
version: '3.7'
