name: black codestyle

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: set up python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black==20.8b1 click==8.0.2

      - name: run codestyle
        run: |
          black --line-length=120 --check .
