name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Tests
      run: docker build . --file deeppavlov_dreamtools/tests/Dockerfile --tag testrunner:latest
    - name: Run Tests
      run: docker run testrunner:latest
